@startuml
title Diagrama de Componentes - Módulo Itinerarios

package "Itinerarios" as Itinerarios {

    package "application" as app {
        package "command" as cmd
        package "service" as svc
        package "useCase" as uc
    }

    package "domain" as dom {
        package "error" as err
        package "model" as mdl
        package "repository" as repo
    }

    package "infraestructure" as infra {
        package "config" as cfg
        package "db" as db
        package "mapper" as mpr
        package "pdf" as pdf
        package "web" as web
    }

    svc --> uc
    uc ..> repo
    repo --> mdl
    repo --> err
    infra --> dom
    web --> svc
    pdf --> mdl
    cfg --> uc
    cfg --> svc
    db ..|> repo

}

package "Destinos" as Destinos {
}

uc ..> Destinos : consulta LugarTuristico

@enduml
