spring.application.name=planificador

server.error.include-message=always

api.version=1.0

spring.profiles.active=dev

spring.main.allow-bean-definition-overriding=true

spring.messages.encoding=UTF-8
spring.messages.basename=messages
